'use client';
import {useState} from 'react';
import {ArrowUpRight,Expand,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import media from '@/lib/media.json';
const descriptions:Record<string,[string,string]>={
'accounts-and-market-quotes':['Accounts & market quotes','Account connectivity, quote snapshots, trade metrics and economic events in the dashboard.'],
'ea-configuration':['EA configuration','Fleet configuration acknowledgements, authorized pairs, sessions and strategy-module controls.'],
'mt5-dual-chart-bridge':['MT5 chart integration','The CelestialNexusBridge overlay attached to two MetaTrader charts. The captured terminal is labelled as a demo account.'],
'mt5-connection-diagnostics':['Terminal diagnostics','The bridge distinguishes cloud connectivity, broker state and terminal trading permissions.'],
'ea-live-bridge':['EA bridge workspace','Chart context, position synchronization, account exposure and signal-delivery visibility.'],
'desktop-command-center':['Desktop command center','The dashboard’s original layout: bridge setup, sessions, news and market quotes.'],
'sign-in':['Platform sign-in','The supplied authentication interface. Provider buttons do not establish that every provider is configured.'],
'command-center':['Command center','Historical dashboard capture showing session context, bridge messages, quotes and account state.'],
'news-and-macro':['News & macro intelligence','Calendar, quotes and session context. The sentiment section is explicitly marked DEMO in this capture.'],
'mobile-command-center':['Mobile dashboard capture','A supplied mobile capture of the command center and account overview.']};
export function ProductEvidence({compact=false}:{compact?:boolean}){const[selected,setSelected]=useState<typeof media[number]|null>(null);const list=compact?media.filter(x=>['desktop-command-center','ea-configuration','mt5-dual-chart-bridge'].includes(x.id)):media;return <div className="product-evidence"><ProductVideo/><div className="evidence-caption"><span className="badge">SUPPLIED PRODUCT CAPTURES</span><p>Historical screenshots, not a live feed. Balances, quotes and results are shown as captured and are not independently verified performance claims.</p></div><div className={compact?'evidence-grid compact':'evidence-grid'}>{list.map(m=><button type="button" className={'evidence-card '+(m.width>m.height?'landscape':'portrait')} key={m.id} onClick={()=>setSelected(m)}><div className="evidence-image"><img src={m.preview} alt={descriptions[m.id][0]+' — historical product screenshot'} width={m.width} height={m.height} loading="lazy"/><span><Expand size={17}/> View full capture</span></div><div className="evidence-card-copy"><h3>{descriptions[m.id][0]}</h3><p>{descriptions[m.id][1]}</p></div></button>)}</div>{compact&&<a className="button outline-button" href="/platform/evidence">View all 10 product captures <ArrowUpRight size={18}/></a>}<Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="evidence-dialog">{selected&&<><DialogTitle>{descriptions[selected.id][0]}</DialogTitle><DialogDescription>{descriptions[selected.id][1]} Historical capture; no live service is connected here.</DialogDescription><div className="evidence-full"><img src={selected.src} alt={descriptions[selected.id][0]} width={selected.width} height={selected.height}/></div><a href={selected.src} target="_blank" rel="noreferrer" className="text-link">Open original image <ArrowUpRight size={16}/></a></>}</DialogContent></Dialog></div>}
export function RuntimeArchitecture(){return <div className="runtime-architecture"><div className="figure-title"><span>ARCHITECTURE VERIFIED IN SOURCE</span><span className="badge">IN DEVELOPMENT</span></div><div className="runtime-columns"><section><span className="eyebrow">01 / CANONICAL DASHBOARD RUNTIME</span><h3>React + Express + PostgreSQL</h3><p>The dashboard and API share a monolithic deployment path configured for Railway.</p><ol>{['React / Vite dashboard','Express API & embedded JOAN','Risk, activation & symbol checks','Durable order bridge','MQL5 EA → MetaTrader → broker','Confirmations & dashboard feedback'].map(x=><li key={x}>{x}</li>)}</ol></section><section><span className="eyebrow">02 / OPTIONAL SERVICE FLEET</span><h3>Python services + event-driven agents</h3><p>The separate fleet has its own application services, JOAN authority and infrastructure definitions.</p><ol>{['FastAPI gateway & services','Kafka signals & agent communication','JOAN fleet authorization','Execution services & Redis queues','PostgreSQL / MongoDB / Weaviate','MLflow & observability stack'].map(x=><li key={x}>{x}</li>)}</ol></section></div><div className="notice">Implemented code is not proof of a running deployment. Research and model outputs remain advisory; connection status alone does not authorize trading.</div></div>}
export function CapabilityEvidence(){return <div className="capability-table"><table><caption>Evidence classifications — reviewed 16 September 2026</caption><thead><tr><th>Component</th><th>Evidence</th><th>Website status</th></tr></thead><tbody>{[['Dashboard & accounts','React screens, API routes and supplied captures','IN DEVELOPMENT'],['JOAN & risk','Embedded authorization, risk sizing and fleet implementation','IN DEVELOPMENT'],['MT5 bridge','MQL5 source, bridge integration and supplied terminal captures','IN DEVELOPMENT'],['Strategy & analytics','Builder, analytics and Research Lab code','IN DEVELOPMENT'],['AWS infrastructure','Terraform for compute, networking and data services','IN DEVELOPMENT'],['Mobile application','Mobile web captures do not establish a native app','ROADMAP'],['Production availability','Current endpoint health and operational readiness not verified','NOT VERIFIED']].map(([a,b,c])=><tr key={a}><th scope="row">{a}</th><td>{b}</td><td><span className="badge">{c}</span></td></tr>)}</tbody></table></div>}

function ProductVideo(){const[failed,setFailed]=useState(false);return <figure className="product-video"><div><span className="badge">RECORDED PRODUCT WALKTHROUGH · 47 SECONDS</span><h3>Inside the Research workspace</h3><p>A supplied screen recording of the platform’s research interface. Displayed controls and model names do not establish trained-model performance or production availability.</p><p>This recording has no audio. It shows the research workspace and its model-selection controls.</p></div><video controls playsInline preload="none" poster="/product/research-walkthrough-poster.jpg" width={502} height={1088} aria-label="Recorded Research workspace walkthrough" onError={()=>setFailed(true)}><source src="/product/research-walkthrough.mp4" type="video/mp4"/>Your browser does not support embedded video.</video><figcaption>{failed&&<p role="status">Video unavailable. Try the download link below.</p>}<a className="text-link" href="/product/research-walkthrough.mp4" download>Download the recording</a> · Historical capture, not a live feed.</figcaption></figure>}
